name: Issue Workflow

on:
  issues:
    types: [opened]

jobs:
  issue-workflow:
    uses: PalisadoesFoundation/.github/.github/workflows/issue.yml@main
    secrets:
      ORG_ACCESS_TOKEN: ${{ secrets.ORG_ACCESS_TOKEN }}
