name: Issue Workflow
on:
  issues:
    types: ['opened']
jobs:
 issue-auto-label:
    uses: yashgoyal0110/.github/.github/workflows/issue.yml@feat/adding-more-centralised-jobs
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}