name: Add Unapproved Label on Unassignment

on:
  issues:
    types: [unassigned]

jobs:
  issue-unassigned:
    uses: PalisadoesFoundation/.github/.github/workflows/issue-unassigned.yml@main
    # secrets:
    #   ORG_ACCESS_TOKEN: ${{ secrets.ORG_ACCESS_TOKEN }}
