##############################################################################
##############################################################################
#
# NOTE!
#
# Please read the README.md file in this directory that defines what should 
# be placed in this file
#
##############################################################################
##############################################################################

name: Issue Assignment Workflow
on:
  issues:
    types: ['assigned']

jobs:
  cleanup-label:
    uses: yashgoyal0110/.github/.github/workflows/issue-assigned.yml@feat/adding-more-centralised-jobs
