name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "*/20 0 * * *"

jobs:
  stale:
    uses: PalisadoesFoundation/.github/.github/workflows/stale.yml@main
    secrets:
      ORG_ACCESS_TOKEN: ${{ secrets.ORG_ACCESS_TOKEN }}
